// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtksQp3K6UW84NDWSWKkQpASHi-PA78k0',
    appId: '1:473674326699:web:ee9b36e05d64a759560dee',
    messagingSenderId: '473674326699',
    projectId: 'votivate-2de44',
    authDomain: 'votivate-2de44.firebaseapp.com',
    storageBucket: 'votivate-2de44.appspot.com',
    measurementId: 'G-CJV73QJR76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwDsIIiLerz7ZSAQZaGHNwDtITvbU9m1c',
    appId: '1:473674326699:android:ca86bc57d78ef331560dee',
    messagingSenderId: '473674326699',
    projectId: 'votivate-2de44',
    storageBucket: 'votivate-2de44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZM9uKq_aM165WgPoUHejnryph4w1dh74',
    appId: '1:473674326699:ios:db10ca7dd632577e560dee',
    messagingSenderId: '473674326699',
    projectId: 'votivate-2de44',
    storageBucket: 'votivate-2de44.appspot.com',
    iosClientId:
        '473674326699-boikocoirm4f4jdpvmtmv3fbj5go2fgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.votingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZM9uKq_aM165WgPoUHejnryph4w1dh74',
    appId: '1:473674326699:ios:33e0be67f56a3086560dee',
    messagingSenderId: '473674326699',
    projectId: 'votivate-2de44',
    storageBucket: 'votivate-2de44.appspot.com',
    iosClientId:
        '473674326699-rn7qkl9hgf3gp5ceamnteqsgbvput4sq.apps.googleusercontent.com',
    iosBundleId: 'com.example.votingApp.RunnerTests',
  );
}
